apiVersion: v1
kind: Service
metadata:  
  labels:
    app: web
  name: web
spec:
  ports:
    - name: "web"
      port: 4200
      targetPort: 4200
  type: LoadBalancer
  selector:
    app: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy: {}
  template:
    metadata:
      labels:
        app: web
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - env:
          - name: SPAENVIRONMENT
            value: local # local environment => SPA (window.env) will be loaded with assets/_environments/local/config.js
        image: web
        name: web
        ports:
          - containerPort: 4200
        resources: {}
        securityContext:
         allowPrivilegeEscalation: false              
      restartPolicy: Always
