trigger: none
pr: none

variables:
# same for every application: artifact group, kubernetesServiceEndpoint and tag variables, and path to migrations Dockerfile
- template: build-variables.yaml@pipeline-templates 

# build/deploy settings
- name: imageName
  value: 'datastewardship'
- name: environment
  value: dev

resources:
  repositories:
  - repository: pipeline-templates
    type: git
    name: pipeline-templates

pool:
  name: linux

stages:

- template: build-stage-template.yaml@pipeline-templates
  parameters:
    imageName: $(imageName)
    tag: $(tag) # from variable template
    # only include what you want to build:
    pathDockerfileApi: '$(Build.SourcesDirectory)/Src/Dockerfile.datastewardship' # full filename

- stage: Deploy
  displayName: Deploy to ${{ upper(variables.environment) }}
  jobs:
  - job: Deploy
    displayName: Deploying application
    workspace:
      clean: all
    steps:
    - template: adb-kubernetes-deploy-kustomize.yaml@pipeline-templates
      parameters:
        kubernetesServiceEndpoint: $(kubernetesServiceEndpoint)
        environment: $(imageName)-$(environment)