# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: default

steps:
- checkout: self
- task: Npm@1
  displayName: Install newman
  inputs:
    command: 'custom'
    workingDir: Tests/Postman
    customCommand: 'install -g newman'
    verbose: false
- task: CmdLine@2
  displayName: Run tests
  inputs:
    workingDirectory: Tests/Postman
    script: newman run Prod.postman_collection.json -x -r junit --reporter-junit-export $(build.artifactstagingdirectory)\Results\JunitResults.xml

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testResultsFiles: '**\*.xml'
    searchFolder: Tests/Postman

#$(build.artifactstagingdirectory)

