apiVersion: skaffold/v4beta5
kind: Config
build:
  artifacts:
  - image: app
    context: ./Src
    docker:
      dockerfile: Dockerfile.status
manifests:
  kustomize:
    paths:
    - ./devops/k8s/local/status
deploy:
  statusCheck: false
  kubeContext: docker-desktop
  kubectl: {}
  helm:
    releases:
    - name: redis
      remoteChart: oci://reg.app.slu.se/oci-charts/redis-standalone
      valuesFiles:
        - ./devops/helm/local/redis/values.yaml
      version: 0.2.1