apiVersion: skaffold/v4beta5
kind: Config
build:
  artifacts:
  - image: web
    context: ./Src
    docker:
      dockerfile: Dockerfile.status.web
manifests:
  rawYaml:
  - ./devops/k8s/local/status.web/*.yaml
deploy:
  statusCheck: false
  kubeContext: docker-desktop
  kubectl: {}
  # helm:
  #   releases:
  #   - name: redis
  #     remoteChart: bitnami/redis
  #     version: 17.3.15
  #     valuesFiles: ["./devops/helm/local/redis/values.yaml"]
