apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sosadminapi-es
  namespace: sosadminapi
spec:
  refreshInterval: "120s"
  secretStoreRef:
    name: kubernetes-p2-artdata-css
    kind: ClusterSecretStore
  target:
    name: sosadminapi-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: kv2/sosadminapi