@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml
title Component diagram for SOS Job Server
Container(api_application, "SOS API Application", "C#, .Net Core", "Provides species observations data via a REST JSON/HTTPS API.")
Container(harvest_api, "SOS Harvest API", "C#, .Net Core", "Provides functionality to change the harvest schedules.")
Container(job_monitoring_application, "Job Server Monitoring Application", "C#, .Net Core", "Provides functionality to monitor the job server.")
System_Ext(observation_data_providers, "Species observation data providers", "Artportalen, WRAM, DwC-A, ...")
System_Ext(processing_data_providers, "Processing data providers", "Dyntaxa DwC-A, Taxon attributes & geography regions")

Container_Boundary(job_server_container, "Job Server") {
    ' Components
    Component(job_server, "SOS.Hangfire.JobServer", ".Net Core service application", "Hangfire job server that executes scheduled & on demand tasks.")
    Component(import_assembly, "SOS.Import", ".Net Core assembly", "Provides functionality for harvesting species observations from various data sources.")
    Component(process_assembly, "SOS.Process", ".Net Core assembly", "Provides functionality for processing verbatim species observations and transform them to DwC format.")
    Component(export_assembly, "SOS.Export", ".Net Core assembly", "Provides functionality for exporting species observations to DwC-A.")

    ' Data storage
    ContainerDb(mongodb_sos_processed, "sos-processed", "MongoDB 4.x", "Stores processed species observations in DwC format")
    ContainerDb(mongodb_sos_verbatim, "sos-verbatim", "MongoDB 4.x", "Stores verbatim harvested species observations")
    Container(doi_file_storage, "DOI File Storage", "Azure BLOB storage", "Stores DOI DwC-A files.\nStored indefinitely.")
    Container(file_storage, "File Storage", "NTFS", "Stores DwC-A files.\nStored 1 week.")

    ' Relations
    Rel(job_server, import_assembly, "Uses")
    Rel(job_server, process_assembly, "Uses")
    Rel(job_server, export_assembly, "Uses")
    Rel(import_assembly, mongodb_sos_verbatim, "Write")
    Rel(process_assembly, mongodb_sos_verbatim, "Read")
    Rel(process_assembly, mongodb_sos_processed, "Write")
    Rel(export_assembly, mongodb_sos_processed, "Read")
    Rel(export_assembly, file_storage, "Write")
    Rel(export_assembly, doi_file_storage, "Write")    
}

'Relations
Rel(import_assembly, observation_data_providers, "Read from", "SQL, HTTPS, File, ...")
Rel(import_assembly, processing_data_providers, "Read from", "HTTPS")
Rel(api_application, job_server, "Adds long running tasks")
Rel(harvest_api, job_server, "Makes API calls to", "JSON/HTTPS")
Rel(job_monitoring_application, job_server, "Makes API calls to", "JSON/HTTPS")
@enduml