apiVersion: apps/v1
kind: Deployment
metadata:
  name: $(imageName)-api
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        slu.se/id: "1003_1"
    spec:
      containers:
      - name: $(imageName)-api
        envFrom:
        - secretRef:
            name: $(imageName)-secret
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: dev
        - name: CorsAllowAny
          value: "true"
        - name: AreaConfiguration
          value: '{"SwedenExtentBufferKm": 200}'
        - name: SosApiConfiguration
          value: |
              {
                  "ObservationsApiAddresses": [ "https://sos-search-dev.wt.artdata.slu.se/" ],
                  "ElasticSearchProxyAddresses": [ "https://sos-proxy-dev.wt.artdata.slu.se/" ],
                  "AnalysisApiAddresses": [ "https://sos-analysis-dev.wt.artdata.slu.se/" ],
                  "DataStewardshipApiAddresses": [ "https://datastewardship-dev.wt.artdata.slu.se/" ]
              }
        - name: ProcessConfiguration
          value: |
              {
                  "TaxonAttributeServiceConfiguration": {
                      "BaseAddress": "https://taxonattributeservice.artdata.slu.se/api",
                      "AcceptHeaderContentType": "application/json"
                  },
                  "TaxonServiceConfiguration": {
                      "BaseAddress": "https://taxonservice.artdata.slu.se/DarwinCore/DarwinCoreArchiveFile?version=custom",
                      "AcceptHeaderContentType": "application/text",
                      "TaxonApiAddress": "https://taxonapi-dev.wt.artdata.slu.se/darwincore/download?version=custom"
                  }
              }
        - name: InputValaidationConfiguration
          value: '{"CountFactor": 1.1, "ElasticSearchMaxRecordsInternal": 100000, "ElasticSearchMaxRecordsPublic": 50000, "MaxBatchSize": 1000, "MaxNrElasticSearchAggregationBuckets": 65535, "SignalSearchTaxonListIds": [ 1, 7, 8, 17, 18 ], "TilesLimitInternal": 350000, "TilesLimitPublic": 65535}'
        - name: CryptoConfiguration
          value: '{"Password": "SECRET_PLACEHOLDER", "Salt": "SECRET_PLACEHOLDER"}'
        - name: ApplicationInsights
          value: |
              {
                  "InstrumentationKey": "SECRET_PLACEHOLDER", 
                  "EnableRequestBodyLogging": false,
                  "EnableSearchResponseCountLogging": false
              }
        - name: ProcessDbConfiguration
          value: |
              {
                  "UserName": "SECRET_PLACEHOLDER", 
                  "Password": "SECRET_PLACEHOLDER", 
                  "Hosts": [
                      {
                          "Name": "artmongo-t-1.artdata.slu.se",
                          "Port": 27017
                      }
                  ], 
                  "ReplicaSetName": null, 
                  "DatabaseName": "sos-dev", 
                  "UseTls": false, 
                  "AuthenticationDb": "admin", 
                  "ReadBatchSize": 10000, 
                  "WriteBatchSize": 10000
              }
        - name: SearchDbConfiguration
          value: '{"UserName": "SECRET_PLACEHOLDER", "Password": "SECRET_PLACEHOLDER", "Clusters": [{"Hosts": ["https://artsearch2-1-test.artdata.slu.se:9200"]}], "DebugMode": true, "IndexPrefix": "sos-dev", "IndexSettings": [{"Name": "observation", "RequestTimeout": 60}]}'
        - name: HangfireDbConfiguration
          value: |
              {
                  "UserName": "SECRET_PLACEHOLDER", 
                  "Password": "SECRET_PLACEHOLDER", 
                  "Hosts": [
                      {
                          "Name": "artmongo-t-1.artdata.slu.se",
                          "Port": 27017
                      }
                  ],
                  "DatabaseName": "sos-hangfire-dev", 
                  "UseTls": false, 
                  "AuthenticationDb": "admin", 
                  "JobExpirationDays": 3
              }
      priorityClassName: high-priority