apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sos-observations-es
  namespace: sos-observations
spec:
  refreshInterval: "120s"
  secretStoreRef:
    name: kubernetes-p2-artdata-css
    kind: ClusterSecretStore
  target:
    name: sos-observations-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: kv2/sos-observations