apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sosadmingui-es
  namespace: sosadmingui-st
spec:
  refreshInterval: "120s"
  secretStoreRef:
    name: kubernetes-t2-artdata-css
    kind: ClusterSecretStore
  target:
    name: sosadmingui-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: kv2/sosadmingui/st