apiVersion: v1
kind: Service
metadata:
  labels:
    app: sos-analysis-api
  name: sos-analysis-api
  namespace: sos-analysis-st
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: sos-analysis-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sos-analysis-api
  name: sos-analysis-api
  namespace: sos-analysis-st
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sos-analysis-api
  strategy: 
      type: Recreate
  template:
    metadata:
      annotations:
        logging: "true"
      labels:
        app: sos-analysis-api
    spec:
      topologySpreadConstraints: # try to spread out api instances over available nodes
      - labelSelector:
          matchLabels:
            app: sos-analysis-api # pods labeled app: sos-analysis-api
        maxSkew: 1
        topologyKey: kubernetes.io/hostname # 1 node = 1 topology
        whenUnsatisfiable: DoNotSchedule
      containers:
        - env:
          - name: ASPNETCORE_ENVIRONMENT
            value: st
          - name: ClientSecret
            valueFrom:
                secretKeyRef:
                  key: ClientSecret
                  name: sos-analysis-secret
          - name: Salt
            valueFrom:
                secretKeyRef:
                  key: Salt
                  name: sos-analysis-secret
          - name: Password
            valueFrom:
                secretKeyRef:
                  key: Password
                  name: sos-analysis-secret
          - name: InstrumentationKey
            valueFrom:
                secretKeyRef:
                  key: InstrumentationKey
                  name: sos-analysis-secret
          - name: ProcessDbPassword
            valueFrom:
                secretKeyRef:
                  key: ProcessDbPassword
                  name: sos-analysis-secret
          - name: ProcessDbUserName
            valueFrom:
                secretKeyRef:
                  key: ProcessDbUserName
                  name: sos-analysis-secret
          - name: SearchDbPassword
            valueFrom:
                secretKeyRef:
                  key: SearchDbPassword
                  name: sos-analysis-secret
          - name: SearchDbUserName
            valueFrom:
                secretKeyRef:
                  key: SearchDbUserName
                  name: sos-analysis-secret
          - name: HangfireDbPassword
            valueFrom:
                secretKeyRef:
                  key: HangfireDbPassword
                  name: sos-analysis-secret
          - name: HangfireDbUserName
            valueFrom:
                secretKeyRef:
                  key: HangfireDbUserName
                  name: sos-analysis-secret
          - name: CorsAllowAny
            value: "true"
          - name: IdentityServer
            value: '{"Authority": "https://login-test.artdata.slu.se", "Audience": "SOS.Observations", "RequireHttpsMetadata": false}'
          - name: AreaConfiguration
            value: '{"SwedenExtentBufferKm": 200}'
          - name: InputValaidationConfiguration
            value: '{"CountFactor": 1.1, "ElasticSearchMaxRecordsInternal": 100000, "ElasticSearchMaxRecordsPublic": 50000, "MaxBatchSize": 1000, "MaxNrElasticSearchAggregationBuckets": 65535, "SignalSearchTaxonListIds": [ 1, 7, 8, 17, 18 ], "TilesLimitInternal": 350000, "TilesLimitPublic": 65535}'
          - name: CryptoConfiguration
            value: '{"Password": "SECRET_PLACEHOLDER", "Salt": "SECRET_PLACEHOLDER"}'
          - name: ApplicationInsights
            value: '{"InstrumentationKey": "SECRET_PLACEHOLDER", "EnableRequestBodyLogging": false, "EnableSearchResponseCountLogging": false}'
          - name: UserServiceConfiguration
            value: '{"BaseAddress": "https://artdatauser-st.artdata.slu.se/api", "AcceptHeaderContentType": "application/json", "UserAdmin2ApiBaseAddress": "https://useradmin2-api-st.wt.artdata.slu.se", "ClientId": "SOS", "ClientSecret": "SECRET_PLACEHOLDER", "Scope": "useradmin.api SOS.Observations.Protected openid", "TokenUrl": "https://useradmin2-auth-st.wt.artdata.slu.se/connect/token", "TokenExpirationBufferInSeconds": 300, "IdentityProvider": {"Authority": "https://useradmin2-auth-st.wt.artdata.slu.se", "Audience": "https://sos-search-st.wt.artdata.slu.se", "RequireHttpsMetadata": false}}'
          - name: SearchDbConfiguration
            value: '{"UserName": "SECRET_PLACEHOLDER", "Password": "SECRET_PLACEHOLDER", "Clusters": [{"Hosts": ["https://artsearch2-1-test.artdata.slu.se:9200"]}], "DebugMode": true, "IndexPrefix": "sos-st", "IndexSettings": [{"Name": "observation", "NumberOfReplicas": 0, "NumberOfShards": 9, "NumberOfShardsProtected": 1, "ReadBatchSize": 10000, "WriteBatchSize": 1000, "RequestTimeout": 300, "ScrollBatchSize": 5000, "ScrollTimeout": "600s"}, {"Name": "dataset", "NumberOfReplicas": 0, "NumberOfShards": 1, "ReadBatchSize": 10000, "WriteBatchSize": 1000, "RequestTimeout": 300, "ScrollBatchSize": 5000, "ScrollTimeout": "600s"}, {"Name": "event", "NumberOfReplicas": 0, "NumberOfShards": 1, "ReadBatchSize": 10000, "WriteBatchSize": 1000, "RequestTimeout": 300, "ScrollBatchSize": 5000, "ScrollTimeout": "600s"}]}'
          - name: ProcessDbConfiguration
            value: '{"UserName": "SECRET_PLACEHOLDER", "Password": "SECRET_PLACEHOLDER", "Hosts": [{"Name": "artmongo-t-1.artdata.slu.se","Port": 27017}], "ReplicaSetName": null, "DatabaseName": "sos-st", "UseTls": false, "AuthenticationDb": "admin", "ReadBatchSize": 10000, "WriteBatchSize": 10000}'
          - name: HangfireDbConfiguration
            value: '{"UserName": "SECRET_PLACEHOLDER", "Password": "SECRET_PLACEHOLDER", "Hosts": [{"Name": "artmongo-t-1.artdata.slu.se","Port": 27017}], "ReplicaSetName": null, "DatabaseName": "sos-hangfire-st", "UseTls": false, "AuthenticationDb": "admin", "JobExpirationDays": 3}'
          image: adbpocreg.azurecr.io/sos-analysis-api:$(Parameters.ImageTag)
          name: sos-analysis-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          readinessProbe: # ready to accept traffic, failure = stops routing traffic to this pod but does not restart the pod!
            httpGet:
              path: /healthz
              port: 5000
              httpHeaders:
              - name: Host
                value: KubernetesReadinessProbe
            initialDelaySeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 30 # runs every 30 seconds
          resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
