apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: dev
        - name: SearchDbConfiguration
          value: '{"UserName": "SECRET_PLACEHOLDER", "Password": "SECRET_PLACEHOLDER", "Clusters": [{"Hosts": ["https://artsearch2-1-test.artdata.slu.se:9200"]}], "DebugMode": true, "IndexPrefix": "sos-dev", "IndexSettings": [{"Name": "observation" ,"RequestTimeout": 60}]}'
        name: api