apiVersion: v1
kind: Service
metadata:
  labels:
    app: sos-proxy-api
  name: sos-proxy-api
  namespace: sos-proxy-st
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: sos-proxy-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sos-proxy-api
  name: sos-proxy-api
  namespace: sos-proxy-st
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sos-proxy-api
  strategy: 
      type: Recreate
  template:
    metadata:
      annotations:
        logging: "true"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/ca-cert: "/vault/tls/ca-bundle.crt"
        vault.hashicorp.com/tls-secret: "vault-ca-bundle"
        vault.hashicorp.com/role: "sos-proxy"
        vault.hashicorp.com/agent-inject-secret-env: "kv2/data/sos-proxy/st"
        vault.hashicorp.com/agent-inject-template-env: |
          {{- with secret "kv2/data/sos-proxy/st" -}}
            {{- range $k, $v := .Data.data -}}
              export {{ $k }}='{{ $v }}'
            {{ end }}
          {{- end }}
      labels:
        app: sos-proxy-api
    spec:
      serviceAccountName: sos-proxy-sa
      topologySpreadConstraints: # try to spread out api instances over available nodes
      - labelSelector:
          matchLabels:
            app: sos-proxy-api # pods labeled app: sos-proxy-api
        maxSkew: 1
        topologyKey: kubernetes.io/hostname # 1 node = 1 topology
        whenUnsatisfiable: DoNotSchedule
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: st
            - name: ApplicationInsights
              value: '{"InstrumentationKey": "SECRET_PLACEHOLDER"}'
            - name: ProcessDbConfiguration
              value: '{"UserName": "SECRET_PLACEHOLDER", "Password": "SECRET_PLACEHOLDER", "Hosts": [{"Name": "artmongo2-1-test.artdata.slu.se","Port": 27017}], "ReplicaSetName": null, "DatabaseName": "sos-st", "UseTls": false, "AuthenticationDb": "admin"}'
            - name: SearchDbConfiguration
              value: '{"UserName": "SECRET_PLACEHOLDER", "Password": "SECRET_PLACEHOLDER", "Clusters": [{"Hosts": ["https://artsearch2-1-test.artdata.slu.se:9200"]}], "DebugMode": true, "IndexPrefix": "sos-st", "IndexSettings": [{"Name": "observation", "RequestTimeout": 60}]}'
          image: adbpocreg.azurecr.io/sos-proxy-api:$(Parameters.ImageTag)
          name: sos-proxy-api
          command: ["sh", "-c"]
          args: [". /vault/secrets/env && dotnet SOS.ElasticSearch.Proxy.dll"]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          readinessProbe: # ready to accept traffic, failure = stops routing traffic to this pod but does not restart the pod!
            httpGet:
              path: /healthz
              port: 5000
              httpHeaders:
              - name: Host
                value: KubernetesReadinessProbe
            initialDelaySeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 30 # runs every 30 seconds
          resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
