namespace SOS.Observations.Api.Helpers
{
    internal static class DwAMappingHelper
    {
        /// <summary>
        /// Map DwA property name to observation property name
        /// </summary>
        /// <param name="field"></param>
        /// <returns></returns>
        public static string MapToObservationField(string field)
        {
            if (string.IsNullOrEmpty(field))
            {
                return null;
            }

            return field.ToLower() switch
            {
                "accessrights" => "accessRights.value",
                "basisofrecord" => "basisOfRecord.value",
                "bibliographiccitation" => "bibliographicCitation",
                "collectioncode" => "collectionCode",
                "collectionid" => "collectionId",
                "datasetid" => "datasetId",
                "datasetname" => "datasetName",
                "informationwithheld" => "informationWithheld",
                "institutioncode" => "institutionCode.value",
                "institutionid = " => "institutionId",
                "language" => "language",
                "license" => "license",
                "modified" => "modified",
                "ownerinstitutioncode" => "ownerInstitutionCode",
                "references" => "references",
                "rightsholder" => "rightsHolder",
                "day" => "event.startDay",
                "enddayofyear" => "event.endDay",
                "eventdate" => "event.startDate",
                "eventid" => "event.eventId",
                "eventremarks" => "event.eventRemarks",
                "eventtime" => "event.plainStartTime",
                "habitat" => "event.habitat",
                "month" => "event.startMonth",
                "parenteventid" => "event.parentEventId",
                "samplesizeunit" => "event.sampleSizeUnit",
                "samplesizevalue" => "event.sampleSizeValue",
                "samplingeffort" => "event.samplingEffort",
                "samplingprotocol" => "event.samplingProtocol",
                "startdayofyear" => "event.startDay",
                "dateidentified" => "identification.dateIdentified",
                "identificationid" => "identification.identificationId",
                "identificationqualifier" => "identification.identificationQualifier",
                "identificationreferences" => "identification.identificationReferences",
                "identificationremarks" => "identification.identificationRemarks",
                "identificationverificationstatus" => "identification.verificationstatus.value",
                "identifiedby" => "identification.identifiedBy",
                "continent" => "location.continent.value",
                "coordinateprecision" => "location.coordinateprecision",
                "coordinateuncertaintyinmeters" => "location.coordinateUncertaintyInMeters",
                "country" => "location.country.value",
                "countrycode" => "location.countryCode",
                "county" => "location.county.name",
                "decimallatitude" => "location.decimalLatitude",
                "decimallongitude" => "location.decimalLongitude",
                "footprintspatialfit" => "location.footprintspatialfit",
                "footprintsrs" => "location.footprintSRS",
                "footprintwkt" => "location.footprintWKT",
                "geodeticdatum" => "location.geodeticDatum",
                "georeferencedby" => "location.georeferencedBy",
                "georeferenceddate" => "location.georeferencedDate",
                "georeferenceprotocol" => "location.georeferenceProtocol",
                "georeferenceremarks" => "location.georeferenceRemarks",
                "georeferencesources" => "location.georeferenceSources",
                "georeferenceverificationstatus" => "location.georeferenceVerificationStatus",
                "highergeography" => "location.higherGeography",
                "highergeographyid" => "location.higherGeographyId",
                "islandgroup" => "location.islandGroup",
                "locality" => "location.locality",
                "locationaccordingto" => "location.locationAccordingTo",
                "locationid" => "location.locationId",
                "locationremarks" => "location.locationremarks",
                "maximumdepthinmeters" => "location.maximumDepthInMeters",
                "maximumdistanceabovesurfaceinmeters" => "location.maximumDistanceAboveSurfaceInMeters",
                "maximumelevationinmeters" => "location.maximumElevationInMeters",
                "minimumdepthinmeters" => "location.minimumDepthInMeters",
                "minimumdistanceabovesurfaceinmeters" => "location.minimumDistanceAboveSurfaceInMeters",
                "minimumelevationinmeters" => "location.minimumElevationInMeters",
                "municipality" => "location.municipality.name",
                "pointradiusspatialfit" => "location.pointradiusspatialfit",
                "stateprovince" => "location.province.name",
                "verbatimlatitude" => "location.verbatimLatitude",
                "verbatimlongitude" => "location.verbatimLongitude",
                "verbatimcoordinatesystem" => "location.verbatimCoordinateSystem",
                "verbatimsrs" => "location.verbatimSRS",
                "materialsampleid" => "materialSample.materialSampleId",
                "associatedmedia" => "occurrence.associatedMedia",
                "associatedoccurrences" => "occurrence.associatedOccurrences",
                "associatedreferences" => "occurrence.associatedreferences",
                "associatedsequences" => "occurrence.associatedSequences",
                "associatedtaxa" => "occurrence.associatedTaxa",
                "behavior" => "occurrence.behavior.value",
                "catalognumber" => "occurrence.catalognumber",
                "individualcount" => "occurrence.individualCount",
                "lifeStage" => "occurrence.lifeStage.value",
                "occurrenceid" => "occurrence.occurrenceId",
                "occurrenceremarks" => "occurrence.occurrenceRemarks",
                "occurrencestatus" => "occurrence.occurrenceStatus.value",
                "organismquantity" => "occurrence.organismQuantity",
                "organismquantitytype" => "occurrence.organismQuantityUnit.value",
                "othercatalognumbers" => "occurrence.otherCatalogNumbers",
                "recordedby" => "occurrence.recordedBy",
                "recordnumber" => "occurrence.recordNumber",
                "reproductivecondition" => "occurrence.reproductivecondition.value",
                "sex" => "occurrence.sex.value",
                "associatedorganisms" => "organism.associatedOrganisms",
                "organismid" => "organism.organismId",
                "organismname" => "organism.organismName",
                "organismremarks" => "organism.organismRemarks",
                "organismscope" => "organism.organismScope",
                "previousidentifications" => "organism.previousidentifications",
                "acceptednameusage" => "taxon.acceptedNameUsage",
                "acceptednameusageid" => "taxon.acceptedNameUsageId",
                "class" => "taxon.class",
                "family" => "taxon.family",
                "genus" => "taxon.genus",
                "higherclassification" => "taxon.higherClassification",
                "infragenericepithet" => "taxon.infraspecificEpithet",
                "infraspecificepithet" => "taxon.infraspecificEpithet",
                "kingdom" => "taxon.kingdom",
                "nameaccordingto" => "taxon.nameAccordingTo",
                "nameaccordingtoid" => "taxon.nameAccordingToId",
                "namepublishedin" => "taxon.namePublishedIn",
                "namepublishedinid" => "taxon.namePublishedInId",
                "namepublishedinyear" => "taxon.namePublishedInYear",
                "order" => "taxon.order",
                "originalnameusage" => "taxon.originalNameUsage",
                "originalnameusageid" => "taxon.originalNameUsageId",
                "parentnameusage" => "taxon.parentNameUsage",
                "parentnameusageid" => "taxon.parentNameUsageId",
                "phylum" => "taxon.phylum",
                "scientificname" => "taxon.scientificName",
                "scientificnameauthorship" => "taxon.scientificNameAuthorship",
                "scientificnameid" => "taxon.scientificNameId",
                "specificepithet" => "taxon.specificEpithet",
                "taxonrank" => "taxon.taxonRank",
                "taxonremarks" => "taxon.taxonRemarks",
                "taxonomicstatus" => "taxon.taxonomicStatus",
                "vernacularname" => "taxon.vernacularName",
                _ => null!
            };
        }
    }
}
