//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorsService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebData", Namespace="http://schemas.datacontract.org/2004/07/ArtDatabanken.WebService.Data")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NorsService.WebSpeciesObservation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NorsService.WebSpeciesObservationField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NorsService.WebSpeciesObservationClass))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NorsService.WebLocale))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NorsService.WebSpeciesObservationProperty))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NorsService.WebSpeciesObservationChange))]
    public partial class WebData : object
    {
        
        private NorsService.WebDataField[] DataFieldsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NorsService.WebDataField[] DataFields
        {
            get
            {
                return this.DataFieldsField;
            }
            set
            {
                this.DataFieldsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebSpeciesObservation", Namespace="http://schemas.datacontract.org/2004/07/ArtDatabanken.WebService.Data")]
    public partial class WebSpeciesObservation : NorsService.WebData
    {
        
        private NorsService.WebSpeciesObservationField[] FieldsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NorsService.WebSpeciesObservationField[] Fields
        {
            get
            {
                return this.FieldsField;
            }
            set
            {
                this.FieldsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebSpeciesObservationField", Namespace="http://schemas.datacontract.org/2004/07/ArtDatabanken.WebService.Data")]
    public partial class WebSpeciesObservationField : NorsService.WebData
    {
        
        private NorsService.WebSpeciesObservationClass ClassField;
        
        private long ClassIndexField;
        
        private string InformationField;
        
        private bool IsClassIndexSpecifiedField;
        
        private bool IsPropertyIndexSpecifiedField;
        
        private NorsService.WebLocale LocaleField;
        
        private NorsService.WebSpeciesObservationProperty PropertyField;
        
        private long PropertyIndexField;
        
        private NorsService.WebDataType TypeField;
        
        private string UnitField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NorsService.WebSpeciesObservationClass Class
        {
            get
            {
                return this.ClassField;
            }
            set
            {
                this.ClassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ClassIndex
        {
            get
            {
                return this.ClassIndexField;
            }
            set
            {
                this.ClassIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Information
        {
            get
            {
                return this.InformationField;
            }
            set
            {
                this.InformationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsClassIndexSpecified
        {
            get
            {
                return this.IsClassIndexSpecifiedField;
            }
            set
            {
                this.IsClassIndexSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPropertyIndexSpecified
        {
            get
            {
                return this.IsPropertyIndexSpecifiedField;
            }
            set
            {
                this.IsPropertyIndexSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NorsService.WebLocale Locale
        {
            get
            {
                return this.LocaleField;
            }
            set
            {
                this.LocaleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NorsService.WebSpeciesObservationProperty Property
        {
            get
            {
                return this.PropertyField;
            }
            set
            {
                this.PropertyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PropertyIndex
        {
            get
            {
                return this.PropertyIndexField;
            }
            set
            {
                this.PropertyIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NorsService.WebDataType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unit
        {
            get
            {
                return this.UnitField;
            }
            set
            {
                this.UnitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebSpeciesObservationClass", Namespace="http://schemas.datacontract.org/2004/07/ArtDatabanken.WebService.Data")]
    public partial class WebSpeciesObservationClass : NorsService.WebData
    {
        
        private NorsService.SpeciesObservationClassId IdField;
        
        private string IdentifierField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NorsService.SpeciesObservationClassId Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identifier
        {
            get
            {
                return this.IdentifierField;
            }
            set
            {
                this.IdentifierField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebLocale", Namespace="http://schemas.datacontract.org/2004/07/ArtDatabanken.WebService.Data")]
    public partial class WebLocale : NorsService.WebData
    {
        
        private string ISOCodeField;
        
        private int IdField;
        
        private string NameField;
        
        private string NativeNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISOCode
        {
            get
            {
                return this.ISOCodeField;
            }
            set
            {
                this.ISOCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NativeName
        {
            get
            {
                return this.NativeNameField;
            }
            set
            {
                this.NativeNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebSpeciesObservationProperty", Namespace="http://schemas.datacontract.org/2004/07/ArtDatabanken.WebService.Data")]
    public partial class WebSpeciesObservationProperty : NorsService.WebData
    {
        
        private NorsService.SpeciesObservationPropertyId IdField;
        
        private string IdentifierField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NorsService.SpeciesObservationPropertyId Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identifier
        {
            get
            {
                return this.IdentifierField;
            }
            set
            {
                this.IdentifierField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebSpeciesObservationChange", Namespace="http://schemas.datacontract.org/2004/07/ArtDatabanken.WebService.Data")]
    public partial class WebSpeciesObservationChange : NorsService.WebData
    {
        
        private NorsService.WebSpeciesObservation[] CreatedSpeciesObservationsField;
        
        private string[] DeletedSpeciesObservationGuidsField;
        
        private long MaxChangeCountField;
        
        private long MaxChangeIdField;
        
        private NorsService.WebSpeciesObservation[] UpdatedSpeciesObservationsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NorsService.WebSpeciesObservation[] CreatedSpeciesObservations
        {
            get
            {
                return this.CreatedSpeciesObservationsField;
            }
            set
            {
                this.CreatedSpeciesObservationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] DeletedSpeciesObservationGuids
        {
            get
            {
                return this.DeletedSpeciesObservationGuidsField;
            }
            set
            {
                this.DeletedSpeciesObservationGuidsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MaxChangeCount
        {
            get
            {
                return this.MaxChangeCountField;
            }
            set
            {
                this.MaxChangeCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MaxChangeId
        {
            get
            {
                return this.MaxChangeIdField;
            }
            set
            {
                this.MaxChangeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NorsService.WebSpeciesObservation[] UpdatedSpeciesObservations
        {
            get
            {
                return this.UpdatedSpeciesObservationsField;
            }
            set
            {
                this.UpdatedSpeciesObservationsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebDataField", Namespace="http://schemas.datacontract.org/2004/07/ArtDatabanken.WebService.Data")]
    public partial class WebDataField : object
    {
        
        private string InformationField;
        
        private string NameField;
        
        private NorsService.WebDataType TypeField;
        
        private string UnitField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Information
        {
            get
            {
                return this.InformationField;
            }
            set
            {
                this.InformationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NorsService.WebDataType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unit
        {
            get
            {
                return this.UnitField;
            }
            set
            {
                this.UnitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebDataType", Namespace="http://schemas.datacontract.org/2004/07/ArtDatabanken.WebService.Data")]
    public enum WebDataType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Boolean = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DateTime = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Float64 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Int32 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Int64 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        String = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpeciesObservationClassId", Namespace="http://schemas.datacontract.org/2004/07/ArtDatabanken.Data")]
    public enum SpeciesObservationClassId : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Conservation = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Event = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeologicalContext = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Identification = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Location = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MeasurementOrFact = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Occurrence = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Project = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResourceRelationship = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DarwinCore = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Taxon = 11,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpeciesObservationPropertyId", Namespace="http://schemas.datacontract.org/2004/07/ArtDatabanken.Data")]
    public enum SpeciesObservationPropertyId : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AcceptedNameUsage = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AcceptedNameUsageID = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessRights = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ActionPlan = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ActivityId = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AssociatedMedia = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AssociatedOccurrences = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AssociatedReferences = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AssociatedSequences = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AssociatedTaxa = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BasisOfRecord = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bed = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Behavior = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BibliographicCitation = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CatalogNumber = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Class = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CollectionCode = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CollectionID = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConservationRelevant = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Continent = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CoordinateM = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CoordinatePrecision = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CoordinateSystemWkt = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CoordinateUncertaintyInMeters = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CoordinateX = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CoordinateY = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CoordinateX_RT90 = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CoordinateY_RT90 = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CoordinateX_SWEREF99 = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CoordinateY_SWEREF99 = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CoordinateX_ETRS89_LAEA = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CoordinateY_ETRS89_LAEA = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CoordinateZ = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Country = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CountryCode = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        County = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataGeneralizations = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatasetID = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatasetName = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DateIdentified = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Day = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DecimalLatitude = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DecimalLongitude = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disposition = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DynamicProperties = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DyntaxaTaxonID = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EarliestAgeOrLowestStage = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EarliestEonOrLowestEonothem = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EarliestEpochOrLowestSeries = 49,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EarliestEraOrLowestErathem = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EarliestPeriodOrLowestSystem = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        End = 52,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EndDayOfYear = 53,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EstablishmentMeans = 54,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EventDate = 55,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EventID = 56,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EventRemarks = 57,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EventTime = 58,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Family = 59,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FieldNotes = 60,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FieldNumber = 61,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Formation = 62,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FootprintSpatialFit = 63,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FootprintSRS = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FootprintWKT = 65,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Genus = 66,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeodeticDatum = 67,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeologicalContextID = 68,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeoreferencedBy = 69,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeoreferencedDate = 70,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeoreferenceProtocol = 71,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeoreferenceRemarks = 72,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeoreferenceSources = 73,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeoreferenceVerificationStatus = 74,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Group = 75,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Habitat = 76,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HigherClassification = 77,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HigherGeography = 78,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HigherGeographyID = 79,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HighestBiostratigraphicZone = 80,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Id = 81,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IdentificationID = 82,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IdentificationQualifier = 83,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IdentificationReferences = 84,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IdentificationRemarks = 85,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IdentificationVerificationStatus = 86,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IdentifiedBy = 87,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IndividualCount = 88,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IndividualID = 89,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InformationWithheld = 90,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InfraspecificEpithet = 91,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstitutionCode = 92,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstitutionID = 93,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Island = 94,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IslandGroup = 95,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IsNaturalOccurrence = 96,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IsNeverFoundObservation = 97,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IsNotRediscoveredObservation = 98,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IsPositiveObservation = 99,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IsPublic = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Kingdom = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Language = 102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LatestAgeOrHighestStage = 103,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LatestEonOrHighestEonothem = 104,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LatestEpochOrHighestSeries = 105,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LatestEraOrHighestErathem = 106,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LatestPeriodOrHighestSystem = 107,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LifeStage = 108,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LithostratigraphicTerms = 109,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Locality = 110,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LocationAccordingTo = 111,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LocationId = 112,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LocationRemarks = 113,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LocationURL = 114,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LowestBiostratigraphicZone = 115,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MaximumDepthInMeters = 116,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MaximumDistanceAboveSurfaceInMeters = 117,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MaximumElevationInMeters = 118,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MeasurementAccuracy = 119,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MeasurementDeterminedBy = 120,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MeasurementDeterminedDate = 121,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MeasurementID = 122,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MeasurementMethod = 123,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MeasurementRemarks = 124,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MeasurementType = 125,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MeasurementUnit = 126,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MeasurementValue = 127,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Member = 128,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MinimumDepthInMeters = 129,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MinimumDistanceAboveSurfaceInMeters = 130,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MinimumElevationInMeters = 131,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modified = 132,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Month = 133,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Municipality = 134,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NameAccordingTo = 135,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NameAccordingToID = 136,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NamePublishedIn = 137,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NamePublishedInID = 138,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NamePublishedInYear = 139,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Natura2000 = 140,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NomenclaturalCode = 141,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NomenclaturalStatus = 142,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OccurrenceID = 143,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OccurrenceRemarks = 144,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OccurrenceStatus = 145,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OccurrenceURL = 146,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Order = 147,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganismGroup = 148,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OriginalNameUsage = 149,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OriginalNameUsageID = 150,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OtherCatalogNumbers = 151,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Owner = 152,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OwnerInstitutionCode = 153,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ParentNameUsage = 154,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ParentNameUsageID = 155,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Parish = 156,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Phylum = 157,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PointRadiusSpatialFit = 158,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Preparations = 159,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PreviousIdentifications = 160,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProjectCategory = 161,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProjectDescription = 162,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProjectEndDate = 163,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProjectID = 164,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProjectName = 165,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProjectOwner = 166,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProjectStartDate = 167,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProjectURL = 168,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProtectedByLaw = 169,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProtectionLevel = 170,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Quantity = 171,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QuantityUnit = 172,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RecordedBy = 173,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RecordNumber = 174,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RedlistCategory = 175,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        References = 176,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RelatedResourceID = 177,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RelationshipAccordingTo = 178,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RelationshipEstablishedDate = 179,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RelationshipOfResource = 180,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RelationshipRemarks = 181,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReportedBy = 182,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReportedDate = 183,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReproductiveCondition = 184,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResourceID = 185,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResourceRelationshipID = 186,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rights = 187,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RightsHolder = 188,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SamplingEffort = 189,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SamplingProtocol = 190,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ScientificName = 191,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ScientificNameAuthorship = 192,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ScientificNameID = 193,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sex = 194,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SpeciesObservationURL = 195,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SpecificEpithet = 196,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Start = 197,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StartDayOfYear = 198,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StateProvince = 199,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Subgenus = 200,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Substrate = 201,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SurveyMethod = 202,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SwedishImmigrationHistory = 203,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SwedishOccurrence = 204,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TaxonConceptID = 205,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TaxonConceptStatus = 206,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TaxonID = 207,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TaxonomicStatus = 208,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TaxonRank = 209,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TaxonRemarks = 210,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TaxonSortOrder = 211,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TaxonURL = 212,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Type = 213,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TypeStatus = 214,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UncertainDetermination = 215,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidationStatus = 216,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerbatimCoordinates = 217,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerbatimCoordinateSystem = 218,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerbatimDepth = 219,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerbatimElevation = 220,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerbatimEventDate = 221,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerbatimLatitude = 222,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerbatimLocality = 223,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerbatimLongitude = 224,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerbatimSRS = 225,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerbatimScientificName = 226,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerbatimTaxonRank = 227,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VernacularName = 228,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WaterBody = 229,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Year = 230,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebGbifObservationChange", Namespace="http://schemas.datacontract.org/2004/07/LifeWatchInterfaceAPI")]
    public partial class WebGbifObservationChange : object
    {
        
        private string[] GbifObservationsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] GbifObservations
        {
            get
            {
                return this.GbifObservationsField;
            }
            set
            {
                this.GbifObservationsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NorsService.ISpeciesObservationChangeService")]
    public interface ISpeciesObservationChangeService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebSpeciesObservation/GetSpeciesObservationChangeAsSpecies", ReplyAction="http://tempuri.org/IWebSpeciesObservation/GetSpeciesObservationChangeAsSpeciesRes" +
            "ponse")]
        System.Threading.Tasks.Task<NorsService.WebSpeciesObservationChange> GetSpeciesObservationChangeAsSpeciesAsync(string token, System.DateTime changedFrom, bool isChangedFromSpecified, System.DateTime changedTo, bool isChangedToSpecified, long changeId, bool isChangedIdSpecified, long maxReturnedChanges);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebSpeciesObservation/GetSpeciesObservationChangeAsGbif", ReplyAction="http://tempuri.org/IWebSpeciesObservation/GetSpeciesObservationChangeAsGbifRespon" +
            "se")]
        System.Threading.Tasks.Task<NorsService.WebGbifObservationChange> GetSpeciesObservationChangeAsGbifAsync(string token, System.DateTime changedFrom, bool isChangedFromSpecified, System.DateTime changedTo, bool isChangedToSpecified, long changeId, bool isChangedIdSpecified, long maxReturnedChanges);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebSpeciesObservation/AreYouThere", ReplyAction="http://tempuri.org/IWebSpeciesObservation/AreYouThereResponse")]
        System.Threading.Tasks.Task<bool> AreYouThereAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebSpeciesObservation/GetServiceVersion", ReplyAction="http://tempuri.org/IWebSpeciesObservation/GetServiceVersionResponse")]
        System.Threading.Tasks.Task<string> GetServiceVersionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebSpeciesObservation/GetServiceVersionAPI", ReplyAction="http://tempuri.org/IWebSpeciesObservation/GetServiceVersionAPIResponse")]
        System.Threading.Tasks.Task<string> GetServiceVersionAPIAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ISpeciesObservationChangeServiceChannel : NorsService.ISpeciesObservationChangeService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SpeciesObservationChangeServiceClient : System.ServiceModel.ClientBase<NorsService.ISpeciesObservationChangeService>, NorsService.ISpeciesObservationChangeService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SpeciesObservationChangeServiceClient() : 
                base(SpeciesObservationChangeServiceClient.GetDefaultBinding(), SpeciesObservationChangeServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISpeciesObservationChangeService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SpeciesObservationChangeServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SpeciesObservationChangeServiceClient.GetBindingForEndpoint(endpointConfiguration), SpeciesObservationChangeServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SpeciesObservationChangeServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SpeciesObservationChangeServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SpeciesObservationChangeServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SpeciesObservationChangeServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SpeciesObservationChangeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<NorsService.WebSpeciesObservationChange> GetSpeciesObservationChangeAsSpeciesAsync(string token, System.DateTime changedFrom, bool isChangedFromSpecified, System.DateTime changedTo, bool isChangedToSpecified, long changeId, bool isChangedIdSpecified, long maxReturnedChanges)
        {
            return base.Channel.GetSpeciesObservationChangeAsSpeciesAsync(token, changedFrom, isChangedFromSpecified, changedTo, isChangedToSpecified, changeId, isChangedIdSpecified, maxReturnedChanges);
        }
        
        public System.Threading.Tasks.Task<NorsService.WebGbifObservationChange> GetSpeciesObservationChangeAsGbifAsync(string token, System.DateTime changedFrom, bool isChangedFromSpecified, System.DateTime changedTo, bool isChangedToSpecified, long changeId, bool isChangedIdSpecified, long maxReturnedChanges)
        {
            return base.Channel.GetSpeciesObservationChangeAsGbifAsync(token, changedFrom, isChangedFromSpecified, changedTo, isChangedToSpecified, changeId, isChangedIdSpecified, maxReturnedChanges);
        }
        
        public System.Threading.Tasks.Task<bool> AreYouThereAsync()
        {
            return base.Channel.AreYouThereAsync();
        }
        
        public System.Threading.Tasks.Task<string> GetServiceVersionAsync()
        {
            return base.Channel.GetServiceVersionAsync();
        }
        
        public System.Threading.Tasks.Task<string> GetServiceVersionAPIAsync()
        {
            return base.Channel.GetServiceVersionAPIAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISpeciesObservationChangeService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISpeciesObservationChangeService))
            {
                return new System.ServiceModel.EndpointAddress("http://aquasupport.slu.se/Nors/SpeciesObservationChangeService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SpeciesObservationChangeServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISpeciesObservationChangeService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SpeciesObservationChangeServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISpeciesObservationChangeService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISpeciesObservationChangeService,
        }
    }
}
